final List<String> symbols = [
  "USD",
  "AUD",
  "DKK",
  "EUR",
  "GBP",
  "CHF",
  "SEK",
  "CAD",
  "KWD",
  "NOK",
  "SAR",
  "JPY",
  "BGN",
  "RON",
  "RUB",
  "IRR",
  "CNY",
  "PKR",
  "QAR",
  "SDR",
];
final List<String> names = [
  "ABD DOLARI ",
  "AVUSTRALYA DOLARI ",
  "DANİMARKA KRONU ",
  "EURO ",
  "İNGİLİZ STERLİNİ ",
  "İSVİÇRE FRANGI	",
  "İSVEÇ KRONU	",
  "KANADA DOLARI	",
  "KUVEYT DİNARI	",
  "NORVEÇ KRONU	",
  "SUUDİ ARABİSTAN RİYALİ	",
  "JAPON YENİ	",
  "BULGAR LEVASI	",
  "RUMEN LEYİ	",
  "RUS RUBLESİ	",
  "İRAN RİYALİ	",
  "ÇİN YUANI	",
  "PAKİSTAN RUPİSİ	",
  "KATAR RİYALİ	",
  "ÖZEL ÇEKME HAKKI",
];

final List<String> flags = [
  'assets/images/flags/USD.png',
  'assets/images/flags/AUD.png',
  'assets/images/flags/DKK.png',
  'assets/images/flags/EUR.png',
  'assets/images/flags/GBP.png',
  'assets/images/flags/CHF.png',
  'assets/images/flags/SEK.png',
  'assets/images/flags/CAD.png',
  'assets/images/flags/KWD.png',
  'assets/images/flags/NOK.png',
  'assets/images/flags/SAR.png',
  'assets/images/flags/JPY.png',
  'assets/images/flags/BGN.png',
  'assets/images/flags/RON.png',
  'assets/images/flags/RUB.png',
  'assets/images/flags/IRR.png',
  'assets/images/flags/CNY.png',
  'assets/images/flags/PKR.png',
  'assets/images/flags/QAR.png',
];
